"""
Catalog of M dwarf planetary systems within 25 pc with:
    - Measured stellar mass with uncertainties
    - Measured stellar rotation period with uncertainties
    - Planet(s) with orbital period < 25 days

All data from peer-reviewed journal articles. GJ 1132 is excluded
(already published in Barnes et al.).

The Engle & Guinan (2023) age-rotation model applies to M0-M6.5 dwarfs.
The Engle (2024) XUV model has two calibrations:
    Early   (M0-M2):     mass >= 0.40 Msun
    MidLate (M2.6-M6.5): mass <  0.40 Msun
"""

LIST_SYSTEMS = [
    {
        "sSystemName": "ProximaCen",
        "sStarName": "Proxima Centauri",
        "sSpectralType": "M5.5V",
        "dDistance": 1.30,
        "dStellarMass": 0.122,
        "dStellarMassSigma": 0.003,
        "dRotationPeriod": 83.2,
        "dRotationPeriodSigma": 1.6,
        "sRotationRef": "Collins et al. (2017), ApJ, 834, 53",
        "sMassRef": "Mann et al. (2015), ApJ, 804, 64",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 11.1868,
                "dOrbPeriodSigma": 0.0008,
                "dMass": 1.07,
                "dMassSigma": 0.06,
                "sRef": "Suarez Mascareno et al. (2020), A&A, 639, A77",
            },
        ],
    },
    {
        "sSystemName": "TRAPPIST-1",
        "sStarName": "TRAPPIST-1",
        "sSpectralType": "M8V",
        "dDistance": 12.43,
        "dStellarMass": 0.0898,
        "dStellarMassSigma": 0.0023,
        "dRotationPeriod": 3.295,
        "dRotationPeriodSigma": 0.003,
        "dAgeOverrideGyr": 7.6,
        "dAgeOverrideSigmaGyr": 2.2,
        "sAgeRef": "Burgasser & Mamajek (2017), ApJ, 845, 110",
        "sRotationRef": "Luger et al. (2017), NatAs, 1, 0129",
        "sMassRef": "Agol et al. (2021), PSJ, 2, 1",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 1.51088,
                "dOrbPeriodSigma": 0.00001,
                "dMass": 1.374,
                "dMassSigma": 0.069,
                "sRef": "Agol et al. (2021)",
            },
            {
                "sName": "c",
                "dOrbPeriod": 2.42182,
                "dOrbPeriodSigma": 0.00001,
                "dMass": 1.308,
                "dMassSigma": 0.056,
                "sRef": "Agol et al. (2021)",
            },
            {
                "sName": "d",
                "dOrbPeriod": 4.04961,
                "dOrbPeriodSigma": 0.00003,
                "dMass": 0.388,
                "dMassSigma": 0.012,
                "sRef": "Agol et al. (2021)",
            },
            {
                "sName": "e",
                "dOrbPeriod": 6.09962,
                "dOrbPeriodSigma": 0.00003,
                "dMass": 0.692,
                "dMassSigma": 0.022,
                "sRef": "Agol et al. (2021)",
            },
            {
                "sName": "f",
                "dOrbPeriod": 9.20669,
                "dOrbPeriodSigma": 0.00005,
                "dMass": 1.039,
                "dMassSigma": 0.031,
                "sRef": "Agol et al. (2021)",
            },
            {
                "sName": "g",
                "dOrbPeriod": 12.35294,
                "dOrbPeriodSigma": 0.00012,
                "dMass": 1.321,
                "dMassSigma": 0.038,
                "sRef": "Agol et al. (2021)",
            },
            {
                "sName": "h",
                "dOrbPeriod": 18.7674,
                "dOrbPeriodSigma": 0.0003,
                "dMass": 0.326,
                "dMassSigma": 0.020,
                "sRef": "Agol et al. (2021)",
            },
        ],
    },
    {
        "sSystemName": "LHS1140",
        "sStarName": "LHS 1140",
        "sSpectralType": "M4.5V",
        "dDistance": 14.99,
        "dStellarMass": 0.179,
        "dStellarMassSigma": 0.014,
        "dRotationPeriod": 131.0,
        "dRotationPeriodSigma": 5.0,
        "sRotationRef": "Dittmann et al. (2017), Nature, 544, 333",
        "sMassRef": "Lillo-Box et al. (2020), A&A, 642, A121",
        "listPlanets": [
            {
                "sName": "c",
                "dOrbPeriod": 3.77793,
                "dOrbPeriodSigma": 0.00004,
                "dMass": 1.81,
                "dMassSigma": 0.39,
                "sRef": "Lillo-Box et al. (2020)",
            },
        ],
    },
    {
        "sSystemName": "GJ1214",
        "sStarName": "GJ 1214",
        "sSpectralType": "M4.5V",
        "dDistance": 14.65,
        "dStellarMass": 0.178,
        "dStellarMassSigma": 0.010,
        "dRotationPeriod": 125.0,
        "dRotationPeriodSigma": 5.0,
        "sRotationRef": "Mallonn et al. (2018), A&A, 614, A35",
        "sMassRef": "Cloutier et al. (2021), AJ, 162, 174",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 1.58040,
                "dOrbPeriodSigma": 0.00001,
                "dMass": 8.17,
                "dMassSigma": 0.43,
                "sRef": "Cloutier et al. (2021)",
            },
        ],
    },
    {
        "sSystemName": "GJ486",
        "sStarName": "GJ 486",
        "sSpectralType": "M3.5V",
        "dDistance": 8.08,
        "dStellarMass": 0.323,
        "dStellarMassSigma": 0.015,
        "dRotationPeriod": 49.9,
        "dRotationPeriodSigma": 5.5,
        "sRotationRef": "Caballero et al. (2022), A&A, 665, A120",
        "sMassRef": "Caballero et al. (2022)",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 1.46714,
                "dOrbPeriodSigma": 0.00003,
                "dMass": 3.00,
                "dMassSigma": 0.13,
                "sRef": "Caballero et al. (2022)",
            },
        ],
    },
    {
        "sSystemName": "GJ367",
        "sStarName": "GJ 367",
        "sSpectralType": "M1V",
        "dDistance": 9.44,
        "dStellarMass": 0.450,
        "dStellarMassSigma": 0.012,
        "dRotationPeriod": 48.0,
        "dRotationPeriodSigma": 2.0,
        "sRotationRef": "Lam et al. (2021), Science, 374, 1271",
        "sMassRef": "Lam et al. (2021)",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 0.32197,
                "dOrbPeriodSigma": 0.00001,
                "dMass": 0.633,
                "dMassSigma": 0.050,
                "sRef": "Goffo et al. (2023), ApJL, 955, L3",
            },
            {
                "sName": "c",
                "dOrbPeriod": 11.543,
                "dOrbPeriodSigma": 0.018,
                "dMass": 4.13,
                "dMassSigma": 0.36,
                "sRef": "Goffo et al. (2023)",
            },
        ],
    },
    {
        "sSystemName": "GJ357",
        "sStarName": "GJ 357",
        "sSpectralType": "M2.5V",
        "dDistance": 9.44,
        "dStellarMass": 0.342,
        "dStellarMassSigma": 0.011,
        "dRotationPeriod": 78.0,
        "dRotationPeriodSigma": 2.0,
        "sRotationRef": "Luque et al. (2019), A&A, 628, A39",
        "sMassRef": "Luque et al. (2019)",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 3.9306,
                "dOrbPeriodSigma": 0.0001,
                "dMass": 1.84,
                "dMassSigma": 0.31,
                "sRef": "Luque et al. (2019)",
            },
        ],
    },
    {
        "sSystemName": "YZCet",
        "sStarName": "YZ Ceti",
        "sSpectralType": "M4.5V",
        "dDistance": 3.72,
        "dStellarMass": 0.130,
        "dStellarMassSigma": 0.009,
        "dRotationPeriod": 68.4,
        "dRotationPeriodSigma": 1.0,
        "sRotationRef": "Stock et al. (2020), A&A, 636, A119",
        "sMassRef": "Stock et al. (2020)",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 2.0208,
                "dOrbPeriodSigma": 0.0002,
                "dMass": 0.70,
                "dMassSigma": 0.08,
                "sRef": "Stock et al. (2020)",
            },
            {
                "sName": "c",
                "dOrbPeriod": 3.0601,
                "dOrbPeriodSigma": 0.0004,
                "dMass": 1.14,
                "dMassSigma": 0.11,
                "sRef": "Stock et al. (2020)",
            },
            {
                "sName": "d",
                "dOrbPeriod": 4.6564,
                "dOrbPeriodSigma": 0.0010,
                "dMass": 1.09,
                "dMassSigma": 0.12,
                "sRef": "Stock et al. (2020)",
            },
        ],
    },
    {
        "sSystemName": "L98-59",
        "sStarName": "L 98-59",
        "sSpectralType": "M3V",
        "dDistance": 10.61,
        "dStellarMass": 0.273,
        "dStellarMassSigma": 0.030,
        "dRotationPeriod": 76.0,
        "dRotationPeriodSigma": 4.0,
        "sRotationRef": "Demangeon et al. (2021), A&A, 653, A41",
        "sMassRef": "Demangeon et al. (2021)",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 2.2531,
                "dOrbPeriodSigma": 0.0001,
                "dMass": 0.40,
                "dMassSigma": 0.16,
                "sRef": "Demangeon et al. (2021)",
            },
            {
                "sName": "c",
                "dOrbPeriod": 3.6906,
                "dOrbPeriodSigma": 0.0002,
                "dMass": 2.22,
                "dMassSigma": 0.26,
                "sRef": "Demangeon et al. (2021)",
            },
            {
                "sName": "d",
                "dOrbPeriod": 7.4507,
                "dOrbPeriodSigma": 0.0005,
                "dMass": 1.94,
                "dMassSigma": 0.28,
                "sRef": "Demangeon et al. (2021)",
            },
        ],
    },
    {
        "sSystemName": "LTT1445A",
        "sStarName": "LTT 1445A",
        "sSpectralType": "M4V",
        "dDistance": 6.86,
        "dStellarMass": 0.257,
        "dStellarMassSigma": 0.014,
        "dRotationPeriod": 85.0,
        "dRotationPeriodSigma": 15.0,
        "sRotationRef": "Winters et al. (2022), AJ, 163, 168",
        "sMassRef": "Winters et al. (2022)",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 5.3588,
                "dOrbPeriodSigma": 0.0002,
                "dMass": 2.87,
                "dMassSigma": 0.25,
                "sRef": "Winters et al. (2022)",
            },
            {
                "sName": "c",
                "dOrbPeriod": 3.1239,
                "dOrbPeriodSigma": 0.0004,
                "dMass": 1.54,
                "dMassSigma": 0.20,
                "sRef": "Winters et al. (2022)",
            },
        ],
    },
    {
        "sSystemName": "GJ436",
        "sStarName": "GJ 436",
        "sSpectralType": "M3.5V",
        "dDistance": 9.76,
        "dStellarMass": 0.445,
        "dStellarMassSigma": 0.029,
        "dRotationPeriod": 44.09,
        "dRotationPeriodSigma": 0.09,
        "sRotationRef": "Bourrier et al. (2018), A&A, 620, A147",
        "sMassRef": "Lanotte et al. (2014), A&A, 572, A73",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 2.64390,
                "dOrbPeriodSigma": 0.00001,
                "dMass": 21.36,
                "dMassSigma": 0.21,
                "sRef": "Lanotte et al. (2014)",
            },
        ],
    },
    {
        "sSystemName": "AUMic",
        "sStarName": "AU Mic",
        "sSpectralType": "M1V",
        "dDistance": 9.72,
        "dStellarMass": 0.500,
        "dStellarMassSigma": 0.030,
        "dRotationPeriod": 4.863,
        "dRotationPeriodSigma": 0.010,
        "dAgeOverrideGyr": 0.022,
        "dAgeOverrideSigmaGyr": 0.003,
        "sAgeRef": "Mamajek & Bell (2014), MNRAS, 445, 2169",
        "sRotationRef": "Plavchan et al. (2020), Nature, 582, 497",
        "sMassRef": "Plavchan et al. (2020)",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 8.4630,
                "dOrbPeriodSigma": 0.0001,
                "dMass": 17.1,
                "dMassSigma": 4.7,
                "sRef": "Cale et al. (2021), AJ, 162, 295",
            },
            {
                "sName": "c",
                "dOrbPeriod": 18.859,
                "dOrbPeriodSigma": 0.002,
                "dMass": 9.6,
                "dMassSigma": 5.8,
                "sRef": "Martioli et al. (2021), A&A, 649, A177",
            },
        ],
    },
]


def fiCountPlanets():
    """Return the total number of planets in the catalog."""
    return sum(len(d["listPlanets"]) for d in LIST_SYSTEMS)


def fiCountSystems():
    """Return the number of systems in the catalog."""
    return len(LIST_SYSTEMS)
