"""
Catalog of M dwarf planetary systems within 25 pc with:
    - Measured stellar mass with uncertainties
    - Measured stellar rotation period with uncertainties
    - Planet(s) with orbital period < 25 days

All data from peer-reviewed journal articles.

The Engle & Guinan (2023) age-rotation model applies to M0-M6.5 dwarfs.
The Engle (2024) XUV model has two calibrations:
    Early   (M0-M2):     mass >= 0.40 Msun
    MidLate (M2.6-M6.5): mass <  0.40 Msun
"""

LIST_SYSTEMS = [
    # ---------------------------------------------------------------
    # Original 12 systems
    # ---------------------------------------------------------------
    {
        "sSystemName": "ProximaCen",
        "sStarName": "Proxima Centauri",
        "sSpectralType": "M5.5V",
        "dDistance": 1.30,
        "dStellarMass": 0.122,
        "dStellarMassSigma": 0.003,
        "dRotationPeriod": 83.2,
        "dRotationPeriodSigma": 1.6,
        "sRotationRef": "Collins et al. (2017), ApJ, 834, 53",
        "sMassRef": "Mann et al. (2015), ApJ, 804, 64",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 11.1868,
                "dOrbPeriodSigma": 0.0008,
                "dMass": 1.07,
                "dMassSigma": 0.06,
                "bMsini": False,
                "sRef": "Suarez Mascareno et al. (2020), A&A, 639, A77",
            },
        ],
    },
    {
        "sSystemName": "TRAPPIST-1",
        "sStarName": "TRAPPIST-1",
        "sSpectralType": "M8V",
        "dDistance": 12.43,
        "dStellarMass": 0.0898,
        "dStellarMassSigma": 0.0023,
        "dRotationPeriod": 3.295,
        "dRotationPeriodSigma": 0.003,
        "dAgeOverrideGyr": 7.6,
        "dAgeOverrideSigmaGyr": 2.2,
        "sAgeRef": "Burgasser & Mamajek (2017), ApJ, 845, 110",
        "sRotationRef": "Luger et al. (2017), NatAs, 1, 0129",
        "sMassRef": "Agol et al. (2021), PSJ, 2, 1",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 1.51088,
                "dOrbPeriodSigma": 0.00001,
                "dMass": 1.374,
                "dMassSigma": 0.069,
                "bMsini": False,
                "sRef": "Agol et al. (2021)",
            },
            {
                "sName": "c",
                "dOrbPeriod": 2.42182,
                "dOrbPeriodSigma": 0.00001,
                "dMass": 1.308,
                "dMassSigma": 0.056,
                "bMsini": False,
                "sRef": "Agol et al. (2021)",
            },
            {
                "sName": "d",
                "dOrbPeriod": 4.04961,
                "dOrbPeriodSigma": 0.00003,
                "dMass": 0.388,
                "dMassSigma": 0.012,
                "bMsini": False,
                "sRef": "Agol et al. (2021)",
            },
            {
                "sName": "e",
                "dOrbPeriod": 6.09962,
                "dOrbPeriodSigma": 0.00003,
                "dMass": 0.692,
                "dMassSigma": 0.022,
                "bMsini": False,
                "sRef": "Agol et al. (2021)",
            },
            {
                "sName": "f",
                "dOrbPeriod": 9.20669,
                "dOrbPeriodSigma": 0.00005,
                "dMass": 1.039,
                "dMassSigma": 0.031,
                "bMsini": False,
                "sRef": "Agol et al. (2021)",
            },
            {
                "sName": "g",
                "dOrbPeriod": 12.35294,
                "dOrbPeriodSigma": 0.00012,
                "dMass": 1.321,
                "dMassSigma": 0.038,
                "bMsini": False,
                "sRef": "Agol et al. (2021)",
            },
            {
                "sName": "h",
                "dOrbPeriod": 18.7674,
                "dOrbPeriodSigma": 0.0003,
                "dMass": 0.326,
                "dMassSigma": 0.020,
                "bMsini": False,
                "sRef": "Agol et al. (2021)",
            },
        ],
    },
    {
        "sSystemName": "LHS1140",
        "sStarName": "LHS 1140",
        "sSpectralType": "M4.5V",
        "dDistance": 14.99,
        "dStellarMass": 0.179,
        "dStellarMassSigma": 0.014,
        "dRotationPeriod": 131.0,
        "dRotationPeriodSigma": 5.0,
        "sRotationRef": "Dittmann et al. (2017), Nature, 544, 333",
        "sMassRef": "Lillo-Box et al. (2020), A&A, 642, A121",
        "listPlanets": [
            {
                "sName": "c",
                "dOrbPeriod": 3.77793,
                "dOrbPeriodSigma": 0.00004,
                "dMass": 1.81,
                "dMassSigma": 0.39,
                "bMsini": False,
                "sRef": "Lillo-Box et al. (2020)",
            },
        ],
    },
    {
        "sSystemName": "GJ1214",
        "sStarName": "GJ 1214",
        "sSpectralType": "M4.5V",
        "dDistance": 14.65,
        "dStellarMass": 0.178,
        "dStellarMassSigma": 0.010,
        "dRotationPeriod": 125.0,
        "dRotationPeriodSigma": 5.0,
        "sRotationRef": "Mallonn et al. (2018), A&A, 614, A35",
        "sMassRef": "Cloutier et al. (2021), AJ, 162, 174",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 1.58040,
                "dOrbPeriodSigma": 0.00001,
                "dMass": 8.17,
                "dMassSigma": 0.43,
                "bMsini": False,
                "sRef": "Cloutier et al. (2021)",
            },
        ],
    },
    {
        "sSystemName": "GJ486",
        "sStarName": "GJ 486",
        "sSpectralType": "M3.5V",
        "dDistance": 8.08,
        "dStellarMass": 0.323,
        "dStellarMassSigma": 0.015,
        "dRotationPeriod": 49.9,
        "dRotationPeriodSigma": 5.5,
        "sRotationRef": "Caballero et al. (2022), A&A, 665, A120",
        "sMassRef": "Caballero et al. (2022)",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 1.46714,
                "dOrbPeriodSigma": 0.00003,
                "dMass": 3.00,
                "dMassSigma": 0.13,
                "bMsini": False,
                "sRef": "Caballero et al. (2022)",
            },
        ],
    },
    {
        "sSystemName": "GJ367",
        "sStarName": "GJ 367",
        "sSpectralType": "M1V",
        "dDistance": 9.44,
        "dStellarMass": 0.450,
        "dStellarMassSigma": 0.012,
        "dRotationPeriod": 48.0,
        "dRotationPeriodSigma": 2.0,
        "sRotationRef": "Lam et al. (2021), Science, 374, 1271",
        "sMassRef": "Lam et al. (2021)",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 0.32197,
                "dOrbPeriodSigma": 0.00001,
                "dMass": 0.633,
                "dMassSigma": 0.050,
                "bMsini": False,
                "sRef": "Goffo et al. (2023), ApJL, 955, L3",
            },
            {
                "sName": "c",
                "dOrbPeriod": 11.543,
                "dOrbPeriodSigma": 0.018,
                "dMass": 4.13,
                "dMassSigma": 0.36,
                "bMsini": False,
                "sRef": "Goffo et al. (2023)",
            },
        ],
    },
    {
        "sSystemName": "GJ357",
        "sStarName": "GJ 357",
        "sSpectralType": "M2.5V",
        "dDistance": 9.44,
        "dStellarMass": 0.342,
        "dStellarMassSigma": 0.011,
        "dRotationPeriod": 78.0,
        "dRotationPeriodSigma": 2.0,
        "sRotationRef": "Luque et al. (2019), A&A, 628, A39",
        "sMassRef": "Luque et al. (2019)",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 3.9306,
                "dOrbPeriodSigma": 0.0001,
                "dMass": 1.84,
                "dMassSigma": 0.31,
                "bMsini": False,
                "sRef": "Luque et al. (2019)",
            },
        ],
    },
    {
        "sSystemName": "YZCet",
        "sStarName": "YZ Ceti",
        "sSpectralType": "M4.5V",
        "dDistance": 3.72,
        "dStellarMass": 0.130,
        "dStellarMassSigma": 0.009,
        "dRotationPeriod": 68.4,
        "dRotationPeriodSigma": 1.0,
        "sRotationRef": "Stock et al. (2020), A&A, 636, A119",
        "sMassRef": "Stock et al. (2020)",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 2.0208,
                "dOrbPeriodSigma": 0.0002,
                "dMass": 0.70,
                "dMassSigma": 0.08,
                "bMsini": False,
                "sRef": "Stock et al. (2020)",
            },
            {
                "sName": "c",
                "dOrbPeriod": 3.0601,
                "dOrbPeriodSigma": 0.0004,
                "dMass": 1.14,
                "dMassSigma": 0.11,
                "bMsini": False,
                "sRef": "Stock et al. (2020)",
            },
            {
                "sName": "d",
                "dOrbPeriod": 4.6564,
                "dOrbPeriodSigma": 0.0010,
                "dMass": 1.09,
                "dMassSigma": 0.12,
                "bMsini": False,
                "sRef": "Stock et al. (2020)",
            },
        ],
    },
    {
        "sSystemName": "L98-59",
        "sStarName": "L 98-59",
        "sSpectralType": "M3V",
        "dDistance": 10.61,
        "dStellarMass": 0.273,
        "dStellarMassSigma": 0.030,
        "dRotationPeriod": 76.0,
        "dRotationPeriodSigma": 4.0,
        "sRotationRef": "Demangeon et al. (2021), A&A, 653, A41",
        "sMassRef": "Demangeon et al. (2021)",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 2.2531,
                "dOrbPeriodSigma": 0.0001,
                "dMass": 0.40,
                "dMassSigma": 0.16,
                "bMsini": False,
                "sRef": "Demangeon et al. (2021)",
            },
            {
                "sName": "c",
                "dOrbPeriod": 3.6906,
                "dOrbPeriodSigma": 0.0002,
                "dMass": 2.22,
                "dMassSigma": 0.26,
                "bMsini": False,
                "sRef": "Demangeon et al. (2021)",
            },
            {
                "sName": "d",
                "dOrbPeriod": 7.4507,
                "dOrbPeriodSigma": 0.0005,
                "dMass": 1.94,
                "dMassSigma": 0.28,
                "bMsini": False,
                "sRef": "Demangeon et al. (2021)",
            },
        ],
    },
    {
        "sSystemName": "LTT1445A",
        "sStarName": "LTT 1445A",
        "sSpectralType": "M4V",
        "dDistance": 6.86,
        "dStellarMass": 0.257,
        "dStellarMassSigma": 0.014,
        "dRotationPeriod": 85.0,
        "dRotationPeriodSigma": 15.0,
        "sRotationRef": "Winters et al. (2022), AJ, 163, 168",
        "sMassRef": "Winters et al. (2022)",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 5.3588,
                "dOrbPeriodSigma": 0.0002,
                "dMass": 2.87,
                "dMassSigma": 0.25,
                "bMsini": False,
                "sRef": "Winters et al. (2022)",
            },
            {
                "sName": "c",
                "dOrbPeriod": 3.1239,
                "dOrbPeriodSigma": 0.0004,
                "dMass": 1.54,
                "dMassSigma": 0.20,
                "bMsini": False,
                "sRef": "Winters et al. (2022)",
            },
        ],
    },
    {
        "sSystemName": "GJ436",
        "sStarName": "GJ 436",
        "sSpectralType": "M3.5V",
        "dDistance": 9.76,
        "dStellarMass": 0.445,
        "dStellarMassSigma": 0.029,
        "dRotationPeriod": 44.09,
        "dRotationPeriodSigma": 0.09,
        "sRotationRef": "Bourrier et al. (2018), A&A, 620, A147",
        "sMassRef": "Lanotte et al. (2014), A&A, 572, A73",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 2.64390,
                "dOrbPeriodSigma": 0.00001,
                "dMass": 21.36,
                "dMassSigma": 0.21,
                "bMsini": False,
                "sRef": "Lanotte et al. (2014)",
            },
        ],
    },
    {
        "sSystemName": "AUMic",
        "sStarName": "AU Mic",
        "sSpectralType": "M1V",
        "dDistance": 9.72,
        "dStellarMass": 0.500,
        "dStellarMassSigma": 0.030,
        "dRotationPeriod": 4.863,
        "dRotationPeriodSigma": 0.010,
        "dAgeOverrideGyr": 0.022,
        "dAgeOverrideSigmaGyr": 0.003,
        "sAgeRef": "Mamajek & Bell (2014), MNRAS, 445, 2169",
        "sRotationRef": "Plavchan et al. (2020), Nature, 582, 497",
        "sMassRef": "Plavchan et al. (2020)",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 8.4630,
                "dOrbPeriodSigma": 0.0001,
                "dMass": 17.1,
                "dMassSigma": 4.7,
                "bMsini": False,
                "sRef": "Cale et al. (2021), AJ, 162, 295",
            },
            {
                "sName": "c",
                "dOrbPeriod": 18.859,
                "dOrbPeriodSigma": 0.002,
                "dMass": 9.6,
                "dMassSigma": 5.8,
                "bMsini": False,
                "sRef": "Martioli et al. (2021), A&A, 649, A177",
            },
        ],
    },
    # ---------------------------------------------------------------
    # New systems sorted by distance
    # ---------------------------------------------------------------
    {
        "sSystemName": "BarnardsStar",
        "sStarName": "Barnard's Star",
        "sSpectralType": "M4V",
        "dDistance": 1.83,
        "dStellarMass": 0.162,
        "dStellarMassSigma": 0.007,
        "dRotationPeriod": 142.0,
        "dRotationPeriodSigma": 8.5,
        "sRotationRef": "Gonzalez-Hernandez et al. (2024), A&A",
        "sMassRef": "Gonzalez-Hernandez et al. (2024), A&A",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 3.1533,
                "dOrbPeriodSigma": 0.0004,
                "dMass": 0.37,
                "dMassSigma": 0.05,
                "bMsini": True,
                "sRef": "Gonzalez-Hernandez et al. (2024)",
            },
        ],
    },
    {
        "sSystemName": "GJ411",
        "sStarName": "GJ 411",
        "sSpectralType": "M2V",
        "dDistance": 2.55,
        "dStellarMass": 0.390,
        "dStellarMassSigma": 0.030,
        "dRotationPeriod": 56.15,
        "dRotationPeriodSigma": 0.27,
        "sRotationRef": "Diaz et al. (2019), A&A, 625, A17",
        "sMassRef": "Diaz et al. (2019), A&A, 625, A17",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 12.939,
                "dOrbPeriodSigma": 0.0014,
                "dMass": 2.69,
                "dMassSigma": 0.19,
                "bMsini": True,
                "sRef": "Hurt et al. (2022); Diaz et al. (2019)",
            },
        ],
    },
    {
        "sSystemName": "GJ887",
        "sStarName": "GJ 887",
        "sSpectralType": "M0.5V",
        "dDistance": 3.29,
        "dStellarMass": 0.495,
        "dStellarMassSigma": 0.049,
        "dRotationPeriod": 38.7,
        "dRotationPeriodSigma": 0.5,
        "sRotationRef": "Jeffers et al. (2020), Science, 368, 1477",
        "sMassRef": "Hartogh et al. (2026)",
        "listPlanets": [
            {
                "sName": "e",
                "dOrbPeriod": 4.4249,
                "dOrbPeriodSigma": 0.00014,
                "dMass": 1.46,
                "dMassSigma": 0.19,
                "bMsini": True,
                "sRef": "Hartogh et al. (2026)",
            },
            {
                "sName": "b",
                "dOrbPeriod": 9.2619,
                "dOrbPeriodSigma": 0.0005,
                "dMass": 3.9,
                "dMassSigma": 0.5,
                "bMsini": True,
                "sRef": "Jeffers et al. (2020); Hartogh et al. (2026)",
            },
            {
                "sName": "c",
                "dOrbPeriod": 21.784,
                "dOrbPeriodSigma": 0.004,
                "dMass": 6.5,
                "dMassSigma": 1.0,
                "bMsini": True,
                "sRef": "Jeffers et al. (2020); Hartogh et al. (2026)",
            },
        ],
    },
    {
        "sSystemName": "Gl725A",
        "sStarName": "Gl 725 A",
        "sSpectralType": "M3V",
        "dDistance": 3.52,
        "dStellarMass": 0.330,
        "dStellarMassSigma": 0.008,
        "dRotationPeriod": 103.1,
        "dRotationPeriodSigma": 6.1,
        "sRotationRef": "Cortes-Zuleta et al. (2025)",
        "sMassRef": "Cortes-Zuleta et al. (2025)",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 11.220,
                "dOrbPeriodSigma": 0.0051,
                "dMass": 2.78,
                "dMassSigma": 0.35,
                "bMsini": True,
                "sRef": "Cortes-Zuleta et al. (2025)",
            },
        ],
    },
    {
        "sSystemName": "GJ1061",
        "sStarName": "GJ 1061",
        "sSpectralType": "M5.5V",
        "dDistance": 3.67,
        "dStellarMass": 0.120,
        "dStellarMassSigma": 0.010,
        "dRotationPeriod": 130.0,
        "dRotationPeriodSigma": 9.5,
        "sRotationRef": "Dreizler et al. (2025), A&A",
        "sMassRef": "Dreizler et al. (2020), MNRAS, 493, 536",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 3.204,
                "dOrbPeriodSigma": 0.001,
                "dMass": 1.37,
                "dMassSigma": 0.16,
                "bMsini": True,
                "sRef": "Dreizler et al. (2020)",
            },
            {
                "sName": "c",
                "dOrbPeriod": 6.689,
                "dOrbPeriodSigma": 0.004,
                "dMass": 1.74,
                "dMassSigma": 0.23,
                "bMsini": True,
                "sRef": "Dreizler et al. (2020)",
            },
            {
                "sName": "d",
                "dOrbPeriod": 13.03,
                "dOrbPeriodSigma": 0.03,
                "dMass": 1.64,
                "dMassSigma": 0.24,
                "bMsini": True,
                "sRef": "Dreizler et al. (2020)",
            },
        ],
    },
    {
        "sSystemName": "Wolf1061",
        "sStarName": "Wolf 1061",
        "sSpectralType": "M3V",
        "dDistance": 4.31,
        "dStellarMass": 0.302,
        "dStellarMassSigma": 0.020,
        "dRotationPeriod": 89.3,
        "dRotationPeriodSigma": 1.8,
        "sRotationRef": "Wright et al. (2016), ApJL, 817, L20",
        "sMassRef": "Wright et al. (2016), ApJL, 817, L20",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 4.887,
                "dOrbPeriodSigma": 0.001,
                "dMass": 1.91,
                "dMassSigma": 0.26,
                "bMsini": True,
                "sRef": "Wright et al. (2016)",
            },
            {
                "sName": "c",
                "dOrbPeriod": 17.87,
                "dOrbPeriodSigma": 0.02,
                "dMass": 3.41,
                "dMassSigma": 0.43,
                "bMsini": True,
                "sRef": "Wright et al. (2016)",
            },
        ],
    },
    {
        "sSystemName": "GJ674",
        "sStarName": "GJ 674",
        "sSpectralType": "M2.5V",
        "dDistance": 4.55,
        "dStellarMass": 0.350,
        "dStellarMassSigma": 0.015,
        "dRotationPeriod": 34.8,
        "dRotationPeriodSigma": 0.4,
        "sRotationRef": "Bonfils et al. (2007), A&A, 474, 293",
        "sMassRef": "Bonfils et al. (2007), A&A, 474, 293",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 4.694,
                "dOrbPeriodSigma": 0.007,
                "dMass": 11.09,
                "dMassSigma": 0.94,
                "bMsini": True,
                "sRef": "Bonfils et al. (2007)",
            },
        ],
    },
    {
        "sSystemName": "GJ876",
        "sStarName": "GJ 876",
        "sSpectralType": "M4V",
        "dDistance": 4.70,
        "dStellarMass": 0.370,
        "dStellarMassSigma": 0.009,
        "dRotationPeriod": 96.7,
        "dRotationPeriodSigma": 1.0,
        "sRotationRef": "Rivera et al. (2005), ApJ, 634, 625",
        "sMassRef": "von Braun et al. (2014), MNRAS, 438, 2413",
        "listPlanets": [
            {
                "sName": "d",
                "dOrbPeriod": 1.9381,
                "dOrbPeriodSigma": 0.0001,
                "dMass": 6.83,
                "dMassSigma": 0.40,
                "bMsini": True,
                "sRef": "Rivera et al. (2010), ApJ, 719, 890",
            },
        ],
    },
    {
        "sSystemName": "GJ1002",
        "sStarName": "GJ 1002",
        "sSpectralType": "M5.5V",
        "dDistance": 4.84,
        "dStellarMass": 0.120,
        "dStellarMassSigma": 0.010,
        "dRotationPeriod": 126.0,
        "dRotationPeriodSigma": 15.0,
        "sRotationRef": "Suarez Mascareno et al. (2023), A&A, 670, A5",
        "sMassRef": "Suarez Mascareno et al. (2023), A&A, 670, A5",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 10.347,
                "dOrbPeriodSigma": 0.027,
                "dMass": 1.08,
                "dMassSigma": 0.13,
                "bMsini": True,
                "sRef": "Suarez Mascareno et al. (2023)",
            },
            {
                "sName": "c",
                "dOrbPeriod": 21.202,
                "dOrbPeriodSigma": 0.013,
                "dMass": 1.36,
                "dMassSigma": 0.17,
                "bMsini": True,
                "sRef": "Suarez Mascareno et al. (2023)",
            },
        ],
    },
    {
        "sSystemName": "GJ251",
        "sStarName": "GJ 251",
        "sSpectralType": "M3V",
        "dDistance": 5.60,
        "dStellarMass": 0.360,
        "dStellarMassSigma": 0.015,
        "dRotationPeriod": 122.1,
        "dRotationPeriodSigma": 2.05,
        "sRotationRef": "Stock et al. (2020), A&A, 643, A112",
        "sMassRef": "Stock et al. (2020), A&A, 643, A112",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 14.237,
                "dOrbPeriodSigma": 0.0015,
                "dMass": 3.85,
                "dMassSigma": 0.35,
                "bMsini": True,
                "sRef": "Stock et al. (2020)",
            },
        ],
    },
    {
        "sSystemName": "GJ581",
        "sStarName": "GJ 581",
        "sSpectralType": "M3V",
        "dDistance": 6.30,
        "dStellarMass": 0.295,
        "dStellarMassSigma": 0.010,
        "dRotationPeriod": 132.5,
        "dRotationPeriodSigma": 6.3,
        "sRotationRef": "von Stauffenberg et al. (2024)",
        "sMassRef": "von Stauffenberg et al. (2024)",
        "listPlanets": [
            {
                "sName": "e",
                "dOrbPeriod": 3.1481,
                "dOrbPeriodSigma": 0.0004,
                "dMass": 2.48,
                "dMassSigma": 0.56,
                "bMsini": True,
                "sRef": "von Stauffenberg et al. (2024)",
            },
            {
                "sName": "b",
                "dOrbPeriod": 5.3686,
                "dOrbPeriodSigma": 0.0001,
                "dMass": 20.5,
                "dMassSigma": 4.9,
                "bMsini": True,
                "sRef": "von Stauffenberg et al. (2024)",
            },
            {
                "sName": "c",
                "dOrbPeriod": 12.921,
                "dOrbPeriodSigma": 0.0008,
                "dMass": 6.81,
                "dMassSigma": 0.69,
                "bMsini": True,
                "sRef": "von Stauffenberg et al. (2024)",
            },
        ],
    },
    {
        "sSystemName": "GJ338B",
        "sStarName": "GJ 338 B",
        "sSpectralType": "M0V",
        "dDistance": 6.33,
        "dStellarMass": 0.640,
        "dStellarMassSigma": 0.070,
        "dRotationPeriod": 16.61,
        "dRotationPeriodSigma": 0.04,
        "sRotationRef": "Gonzalez-Alvarez et al. (2020), A&A, 637, A93",
        "sMassRef": "Gonzalez-Alvarez et al. (2020), A&A, 637, A93",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 24.45,
                "dOrbPeriodSigma": 0.14,
                "dMass": 10.27,
                "dMassSigma": 1.43,
                "bMsini": True,
                "sRef": "Gonzalez-Alvarez et al. (2020)",
            },
        ],
    },
    {
        "sSystemName": "GJ625",
        "sStarName": "GJ 625",
        "sSpectralType": "M2V",
        "dDistance": 6.47,
        "dStellarMass": 0.320,
        "dStellarMassSigma": 0.020,
        "dRotationPeriod": 77.8,
        "dRotationPeriodSigma": 5.5,
        "sRotationRef": "Suarez Mascareno et al. (2017), A&A, 605, A92",
        "sMassRef": "Suarez Mascareno et al. (2017), A&A, 605, A92",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 14.628,
                "dOrbPeriodSigma": 0.013,
                "dMass": 2.82,
                "dMassSigma": 0.51,
                "bMsini": True,
                "sRef": "Suarez Mascareno et al. (2017)",
            },
        ],
    },
    {
        "sSystemName": "GJ393",
        "sStarName": "GJ 393",
        "sSpectralType": "M2V",
        "dDistance": 7.03,
        "dStellarMass": 0.370,
        "dStellarMassSigma": 0.013,
        "dRotationPeriod": 34.0,
        "dRotationPeriodSigma": 0.1,
        "sRotationRef": "Amado et al. (2021), A&A, 650, A188",
        "sMassRef": "Amado et al. (2021), A&A, 650, A188",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 7.027,
                "dOrbPeriodSigma": 0.001,
                "dMass": 1.71,
                "dMassSigma": 0.24,
                "bMsini": True,
                "sRef": "Amado et al. (2021)",
            },
        ],
    },
    {
        "sSystemName": "GJ4274",
        "sStarName": "GJ 4274",
        "sSpectralType": "M4V",
        "dDistance": 7.23,
        "dStellarMass": 0.180,
        "dStellarMassSigma": 0.030,
        "dRotationPeriod": 4.600,
        "dRotationPeriodSigma": 0.009,
        "sRotationRef": "Charpentier et al. (2026)",
        "sMassRef": "Charpentier et al. (2026)",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 1.6339,
                "dOrbPeriodSigma": 0.0001,
                "dMass": 2.97,
                "dMassSigma": 0.52,
                "bMsini": True,
                "sRef": "Charpentier et al. (2026)",
            },
        ],
    },
    {
        "sSystemName": "G192-15",
        "sStarName": "G 192-15",
        "sSpectralType": "M5.5V",
        "dDistance": 9.53,
        "dStellarMass": 0.132,
        "dStellarMassSigma": 0.009,
        "dRotationPeriod": 105.0,
        "dRotationPeriodSigma": 6.0,
        "sRotationRef": "Kaminski et al. (2025)",
        "sMassRef": "Kaminski et al. (2025)",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 2.2748,
                "dOrbPeriodSigma": 0.00027,
                "dMass": 1.03,
                "dMassSigma": 0.18,
                "bMsini": True,
                "sRef": "Kaminski et al. (2025)",
            },
        ],
    },
    {
        "sSystemName": "Wolf1069",
        "sStarName": "Wolf 1069",
        "sSpectralType": "M5V",
        "dDistance": 9.57,
        "dStellarMass": 0.167,
        "dStellarMassSigma": 0.011,
        "dRotationPeriod": 169.3,
        "dRotationPeriodSigma": 3.65,
        "sRotationRef": "Kossakowski et al. (2023), A&A, 670, A84",
        "sMassRef": "Kossakowski et al. (2023), A&A, 670, A84",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 15.564,
                "dOrbPeriodSigma": 0.015,
                "dMass": 1.26,
                "dMassSigma": 0.21,
                "bMsini": True,
                "sRef": "Kossakowski et al. (2023)",
            },
        ],
    },
    {
        "sSystemName": "Gl49",
        "sStarName": "Gl 49",
        "sSpectralType": "M1.5V",
        "dDistance": 9.90,
        "dStellarMass": 0.515,
        "dStellarMassSigma": 0.019,
        "dRotationPeriod": 18.86,
        "dRotationPeriodSigma": 0.095,
        "sRotationRef": "Perger et al. (2019), A&A, 624, A123",
        "sMassRef": "Perger et al. (2019), A&A, 624, A123",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 13.851,
                "dOrbPeriodSigma": 0.005,
                "dMass": 5.63,
                "dMassSigma": 0.68,
                "bMsini": True,
                "sRef": "Perger et al. (2019)",
            },
        ],
    },
    {
        "sSystemName": "GJ3988",
        "sStarName": "GJ 3988",
        "sSpectralType": "M5V",
        "dDistance": 9.90,
        "dStellarMass": 0.184,
        "dStellarMassSigma": 0.015,
        "dRotationPeriod": 116.0,
        "dRotationPeriodSigma": 3.0,
        "sRotationRef": "Gorrini et al. (2023), A&A, 680, A28",
        "sMassRef": "Gorrini et al. (2023), A&A, 680, A28",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 6.9442,
                "dOrbPeriodSigma": 0.001,
                "dMass": 3.69,
                "dMassSigma": 0.42,
                "bMsini": True,
                "sRef": "Gorrini et al. (2023)",
            },
        ],
    },
    {
        "sSystemName": "HD260655",
        "sStarName": "HD 260655",
        "sSpectralType": "M0V",
        "dDistance": 10.0,
        "dStellarMass": 0.600,
        "dStellarMassSigma": 0.020,
        "dRotationPeriod": 37.5,
        "dRotationPeriodSigma": 0.4,
        "sRotationRef": "Luque et al. (2022), A&A, 664, A199",
        "sMassRef": "Luque et al. (2022), A&A, 664, A199",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 2.7695,
                "dOrbPeriodSigma": 0.00003,
                "dMass": 2.14,
                "dMassSigma": 0.34,
                "bMsini": False,
                "sRef": "Luque et al. (2022)",
            },
            {
                "sName": "c",
                "dOrbPeriod": 5.7059,
                "dOrbPeriodSigma": 0.00007,
                "dMass": 3.09,
                "dMassSigma": 0.48,
                "bMsini": False,
                "sRef": "Luque et al. (2022)",
            },
        ],
    },
    {
        "sSystemName": "GJ536",
        "sStarName": "GJ 536",
        "sSpectralType": "M1V",
        "dDistance": 10.0,
        "dStellarMass": 0.520,
        "dStellarMassSigma": 0.050,
        "dRotationPeriod": 43.3,
        "dRotationPeriodSigma": 0.06,
        "sRotationRef": "Suarez Mascareno et al. (2017), A&A, 597, A108",
        "sMassRef": "Suarez Mascareno et al. (2017), A&A, 597, A108",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 8.709,
                "dOrbPeriodSigma": 0.001,
                "dMass": 6.37,
                "dMassSigma": 0.38,
                "bMsini": True,
                "sRef": "Suarez Mascareno et al. (2017)",
            },
        ],
    },
    {
        "sSystemName": "GJ740",
        "sStarName": "GJ 740",
        "sSpectralType": "M0.5V",
        "dDistance": 11.10,
        "dStellarMass": 0.580,
        "dStellarMassSigma": 0.060,
        "dRotationPeriod": 35.563,
        "dRotationPeriodSigma": 0.071,
        "sRotationRef": "Toledo-Padron et al. (2021), A&A, 648, A20",
        "sMassRef": "Toledo-Padron et al. (2021), A&A, 648, A20",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 2.3776,
                "dOrbPeriodSigma": 0.00012,
                "dMass": 2.96,
                "dMassSigma": 0.49,
                "bMsini": True,
                "sRef": "Toledo-Padron et al. (2021)",
            },
        ],
    },
    {
        "sSystemName": "LHS475",
        "sStarName": "LHS 475",
        "sSpectralType": "M3V",
        "dDistance": 12.48,
        "dStellarMass": 0.262,
        "dStellarMassSigma": 0.021,
        "dRotationPeriod": 79.32,
        "dRotationPeriodSigma": 0.02,
        "sRotationRef": "Ment et al. (2024), AJ, 167, 197",
        "sMassRef": "Lustig-Yaeger et al. (2023), Nature Astronomy, 7, 1317",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 2.029,
                "dOrbPeriodSigma": 0.0001,
                "dMass": None,
                "dMassSigma": None,
                "bMsini": False,
                "sRef": "Lustig-Yaeger et al. (2023)",
            },
        ],
    },
    {
        "sSystemName": "GJ1132",
        "sStarName": "GJ 1132",
        "sSpectralType": "M4.5V",
        "dDistance": 12.61,
        "dStellarMass": 0.181,
        "dStellarMassSigma": 0.019,
        "dRotationPeriod": 122.3,
        "dRotationPeriodSigma": 5.5,
        "sRotationRef": "Berta-Thompson et al. (2015), Nature, 527, 204",
        "sMassRef": "Berta-Thompson et al. (2015), Nature, 527, 204",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 1.62893,
                "dOrbPeriodSigma": 0.00001,
                "dMass": 1.66,
                "dMassSigma": 0.23,
                "bMsini": False,
                "sRef": "Berta-Thompson et al. (2015)",
            },
            {
                "sName": "c",
                "dOrbPeriod": 8.929,
                "dOrbPeriodSigma": 0.010,
                "dMass": 2.64,
                "dMassSigma": 0.44,
                "bMsini": True,
                "sRef": "Bonfils et al. (2018), A&A, 618, A142",
            },
        ],
    },
    {
        "sSystemName": "GJ3779",
        "sStarName": "GJ 3779",
        "sSpectralType": "M4V",
        "dDistance": 13.74,
        "dStellarMass": 0.270,
        "dStellarMassSigma": 0.020,
        "dRotationPeriod": 95.0,
        "dRotationPeriodSigma": 5.0,
        "sRotationRef": "Luque et al. (2018), A&A, 620, A171",
        "sMassRef": "Luque et al. (2018), A&A, 620, A171",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 3.0232,
                "dOrbPeriodSigma": 0.0013,
                "dMass": 8.0,
                "dMassSigma": 0.5,
                "bMsini": True,
                "sRef": "Luque et al. (2018)",
            },
        ],
    },
    {
        "sSystemName": "TOI-540",
        "sStarName": "TOI-540",
        "sSpectralType": "M4V",
        "dDistance": 14.01,
        "dStellarMass": 0.159,
        "dStellarMassSigma": 0.014,
        "dRotationPeriod": 0.7261,
        "dRotationPeriodSigma": 0.0004,
        "dAgeOverrideGyr": 0.6,
        "dAgeOverrideSigmaGyr": 0.4,
        "sAgeRef": "Ment et al. (2021), AJ, 161, 23",
        "sRotationRef": "Ment et al. (2021), AJ, 161, 23",
        "sMassRef": "Ment et al. (2021), AJ, 161, 23",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 1.2391,
                "dOrbPeriodSigma": 0.000002,
                "dMass": None,
                "dMassSigma": None,
                "bMsini": False,
                "sRef": "Ment et al. (2021)",
            },
        ],
    },
    {
        "sSystemName": "GJ685",
        "sStarName": "GJ 685",
        "sSpectralType": "M1V",
        "dDistance": 14.32,
        "dStellarMass": 0.554,
        "dStellarMassSigma": 0.020,
        "dRotationPeriod": 18.15,
        "dRotationPeriodSigma": 0.155,
        "sRotationRef": "Pinamonti et al. (2019), A&A, 625, A126",
        "sMassRef": "Pinamonti et al. (2019), A&A, 625, A126",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 24.16,
                "dOrbPeriodSigma": 0.054,
                "dMass": 9.0,
                "dMassSigma": 1.75,
                "bMsini": True,
                "sRef": "Pinamonti et al. (2019)",
            },
        ],
    },
    {
        "sSystemName": "LHS3844",
        "sStarName": "LHS 3844",
        "sSpectralType": "M5V",
        "dDistance": 14.89,
        "dStellarMass": 0.158,
        "dStellarMassSigma": 0.020,
        "dRotationPeriod": 128.0,
        "dRotationPeriodSigma": 24.0,
        "sRotationRef": "Vanderspek et al. (2019), ApJL, 871, L24",
        "sMassRef": "Vanderspek et al. (2019), ApJL, 871, L24",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 0.46293,
                "dOrbPeriodSigma": 0.00001,
                "dMass": None,
                "dMassSigma": None,
                "bMsini": False,
                "sRef": "Vanderspek et al. (2019)",
            },
        ],
    },
    {
        "sSystemName": "GJ238",
        "sStarName": "GJ 238",
        "sSpectralType": "M2.5V",
        "dDistance": 15.22,
        "dStellarMass": 0.419,
        "dStellarMassSigma": 0.010,
        "dRotationPeriod": 44.0,
        "dRotationPeriodSigma": 2.0,
        "sRotationRef": "Tey et al. (2024), AJ, 167, 283",
        "sMassRef": "Tey et al. (2024), AJ, 167, 283",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 1.7447,
                "dOrbPeriodSigma": 0.000002,
                "dMass": None,
                "dMassSigma": None,
                "bMsini": False,
                "sRef": "Tey et al. (2024)",
            },
        ],
    },
    {
        "sSystemName": "GJ720A",
        "sStarName": "GJ 720 A",
        "sSpectralType": "M0.5V",
        "dDistance": 15.56,
        "dStellarMass": 0.603,
        "dStellarMassSigma": 0.048,
        "dRotationPeriod": 36.05,
        "dRotationPeriodSigma": 1.41,
        "sRotationRef": "Gonzalez-Alvarez et al. (2021), A&A, 649, A157",
        "sMassRef": "Gonzalez-Alvarez et al. (2021), A&A, 649, A157",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 19.466,
                "dOrbPeriodSigma": 0.005,
                "dMass": 13.64,
                "dMassSigma": 0.79,
                "bMsini": True,
                "sRef": "Gonzalez-Alvarez et al. (2021)",
            },
        ],
    },
    {
        "sSystemName": "HD238090",
        "sStarName": "HD 238090",
        "sSpectralType": "M1V",
        "dDistance": 15.70,
        "dStellarMass": 0.578,
        "dStellarMassSigma": 0.021,
        "dRotationPeriod": 96.7,
        "dRotationPeriodSigma": 3.45,
        "sRotationRef": "Stock et al. (2020), A&A, 643, A112",
        "sMassRef": "Stock et al. (2020), A&A, 643, A112",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 13.671,
                "dOrbPeriodSigma": 0.011,
                "dMass": 6.89,
                "dMassSigma": 0.94,
                "bMsini": True,
                "sRef": "Stock et al. (2020)",
            },
        ],
    },
    {
        "sSystemName": "G264-012",
        "sStarName": "G 264-012",
        "sSpectralType": "M4V",
        "dDistance": 16.01,
        "dStellarMass": 0.297,
        "dStellarMassSigma": 0.024,
        "dRotationPeriod": 100.0,
        "dRotationPeriodSigma": 6.0,
        "sRotationRef": "Amado et al. (2021), A&A, 650, A188",
        "sMassRef": "Amado et al. (2021), A&A, 650, A188",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 2.3054,
                "dOrbPeriodSigma": 0.00031,
                "dMass": 2.50,
                "dMassSigma": 0.30,
                "bMsini": True,
                "sRef": "Amado et al. (2021)",
            },
            {
                "sName": "c",
                "dOrbPeriod": 8.0518,
                "dOrbPeriodSigma": 0.0034,
                "dMass": 3.75,
                "dMassSigma": 0.48,
                "bMsini": True,
                "sRef": "Amado et al. (2021)",
            },
        ],
    },
    {
        "sSystemName": "GJ3942",
        "sStarName": "GJ 3942",
        "sSpectralType": "M0V",
        "dDistance": 16.93,
        "dStellarMass": 0.569,
        "dStellarMassSigma": 0.020,
        "dRotationPeriod": 16.3,
        "dRotationPeriodSigma": 0.22,
        "sRotationRef": "Perger et al. (2017), A&A, 608, A63",
        "sMassRef": "Perger et al. (2017), A&A, 608, A63",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 6.905,
                "dOrbPeriodSigma": 0.004,
                "dMass": 7.1,
                "dMassSigma": 0.81,
                "bMsini": True,
                "sRef": "Perger et al. (2017)",
            },
        ],
    },
    {
        "sSystemName": "GJ724",
        "sStarName": "GJ 724",
        "sSpectralType": "M1V",
        "dDistance": 17.0,
        "dStellarMass": 0.550,
        "dStellarMassSigma": 0.040,
        "dRotationPeriod": 57.0,
        "dRotationPeriodSigma": 1.0,
        "sRotationRef": "Gorrini et al. (2023), A&A, 680, A28",
        "sMassRef": "Gorrini et al. (2023), A&A, 680, A28",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 5.1013,
                "dOrbPeriodSigma": 0.00008,
                "dMass": 10.75,
                "dMassSigma": 0.92,
                "bMsini": True,
                "sRef": "Gorrini et al. (2023)",
            },
        ],
    },
    {
        "sSystemName": "GJ1252",
        "sStarName": "GJ 1252",
        "sSpectralType": "M3V",
        "dDistance": 20.37,
        "dStellarMass": 0.381,
        "dStellarMassSigma": 0.019,
        "dRotationPeriod": 64.0,
        "dRotationPeriodSigma": 4.0,
        "sRotationRef": "Shporer et al. (2020), ApJL, 890, L7",
        "sMassRef": "Shporer et al. (2020), ApJL, 890, L7",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 0.5182,
                "dOrbPeriodSigma": 0.0000084,
                "dMass": 1.32,
                "dMassSigma": 0.28,
                "bMsini": False,
                "sRef": "Shporer et al. (2020)",
            },
        ],
    },
    {
        "sSystemName": "GJ4276",
        "sStarName": "GJ 4276",
        "sSpectralType": "M2V",
        "dDistance": 21.35,
        "dStellarMass": 0.406,
        "dStellarMassSigma": 0.030,
        "dRotationPeriod": 64.6,
        "dRotationPeriodSigma": 1.7,
        "sRotationRef": "Nagel et al. (2019), A&A, 622, A153",
        "sMassRef": "Nagel et al. (2019), A&A, 622, A153",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 13.352,
                "dOrbPeriodSigma": 0.003,
                "dMass": 16.57,
                "dMassSigma": 0.95,
                "bMsini": True,
                "sRef": "Nagel et al. (2019)",
            },
        ],
    },
    {
        "sSystemName": "K2-415",
        "sStarName": "K2-415",
        "sSpectralType": "M5V",
        "dDistance": 21.82,
        "dStellarMass": 0.164,
        "dStellarMassSigma": 0.004,
        "dRotationPeriod": 4.298,
        "dRotationPeriodSigma": 0.061,
        "dAgeOverrideGyr": 0.8,
        "dAgeOverrideSigmaGyr": 0.5,
        "sAgeRef": "Hirano et al. (2023), AJ, 165, 131",
        "sRotationRef": "Hirano et al. (2023), AJ, 165, 131",
        "sMassRef": "Hirano et al. (2023), AJ, 165, 131",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 4.018,
                "dOrbPeriodSigma": 0.000003,
                "dMass": None,
                "dMassSigma": None,
                "bMsini": False,
                "sRef": "Hirano et al. (2023)",
            },
        ],
    },
    {
        "sSystemName": "TOI-244",
        "sStarName": "TOI-244",
        "sSpectralType": "M2.5V",
        "dDistance": 22.0,
        "dStellarMass": 0.427,
        "dStellarMassSigma": 0.029,
        "dRotationPeriod": 53.3,
        "dRotationPeriodSigma": 1.15,
        "sRotationRef": "Castro-Gonzalez et al. (2023), A&A, 675, A52",
        "sMassRef": "Castro-Gonzalez et al. (2023), A&A, 675, A52",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 7.3972,
                "dOrbPeriodSigma": 0.000025,
                "dMass": 2.68,
                "dMassSigma": 0.30,
                "bMsini": False,
                "sRef": "Castro-Gonzalez et al. (2023)",
            },
        ],
    },
    {
        "sSystemName": "GJ3090",
        "sStarName": "GJ 3090",
        "sSpectralType": "M2V",
        "dDistance": 22.48,
        "dStellarMass": 0.519,
        "dStellarMassSigma": 0.013,
        "dRotationPeriod": 17.95,
        "dRotationPeriodSigma": 0.15,
        "sRotationRef": "Almenara et al. (2022), A&A, 665, A91",
        "sMassRef": "Almenara et al. (2022), A&A, 665, A91",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 2.8531,
                "dOrbPeriodSigma": 0.000001,
                "dMass": 4.52,
                "dMassSigma": 0.47,
                "bMsini": False,
                "sRef": "Almenara et al. (2022)",
            },
        ],
    },
    {
        "sSystemName": "TOI-4336A",
        "sStarName": "TOI-4336 A",
        "sSpectralType": "M3.5V",
        "dDistance": 22.55,
        "dStellarMass": 0.306,
        "dStellarMassSigma": 0.008,
        "dRotationPeriod": 35.5,
        "dRotationPeriodSigma": 1.1,
        "sRotationRef": "Parc et al. (2026), A&A",
        "sMassRef": "Parc et al. (2026), A&A",
        "listPlanets": [
            {
                "sName": "c",
                "dOrbPeriod": 7.5873,
                "dOrbPeriodSigma": 0.000012,
                "dMass": 1.55,
                "dMassSigma": 0.13,
                "bMsini": False,
                "sRef": "Parc et al. (2026)",
            },
        ],
    },
    {
        "sSystemName": "TOI-198",
        "sStarName": "TOI-198",
        "sSpectralType": "M2V",
        "dDistance": 23.73,
        "dStellarMass": 0.467,
        "dStellarMassSigma": 0.023,
        "dRotationPeriod": 48.5,
        "dRotationPeriodSigma": 1.0,
        "sRotationRef": "Zapatero Osorio et al. (2026), A&A, 706, A166",
        "sMassRef": "Oddo et al. (2023), AJ",
        "listPlanets": [
            {
                "sName": "b",
                "dOrbPeriod": 10.215,
                "dOrbPeriodSigma": 0.00006,
                "dMass": 2.67,
                "dMassSigma": None,
                "bMsini": False,
                "sRef": "Oddo et al. (2023)",
            },
        ],
    },
]


def fiCountPlanets():
    """Return the total number of planets in the catalog."""
    return sum(len(d["listPlanets"]) for d in LIST_SYSTEMS)


def fiCountSystems():
    """Return the number of systems in the catalog."""
    return len(LIST_SYSTEMS)
